# change localhost server port number
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
#      "create" will fix and create sql table automatically (logging option below will show the fixed table in console)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG  # For logging SQL statements.
    org.hibernate.type: TRACE  # For logging the bound parameters among others (optional, can be verbose).
    org.hibernate.tool.hbm2ddl: DEBUG  # Important for logging schema export (DDL) statements.